### ISSUE TITLE
Add ability to connect to Ledger

### ISSUE THREAD

**Issue by noisypigeon** [noisypigeon-inc/wallet#12]
## Acceptance Criteria

The user should be able to connect to the Celo application on their Ledger and see their Celo address in Pigeon. 

## Tasks

- [ ] Implement Ethereum <> Celo adapter for Ledger application. See https://github.com/celo-tools/celo-web-wallet/blob/master/src/features/ledger/CeloLedgerApp.ts.
- [ ] Implement support for transportation protocols (Bluetooth, USB).
- [ ] Implement basic transaction support for fetching Celo address.
- [ ] Implement user interface for selecting Ledger model and connection method.

Should be acknowledged that the Nano S has no Bluetooth functionality and USB is not supported on iOS. More details can be found [here](https://cryptosec.info/ledger-nano-s-iphone/).
