### ISSUE TITLE
Setup React Native Project

### ISSUE THREAD

**Issue by noisypigeon** [noisypigeon-inc/wallet#2]
- [x] Create React Native project using TypeScript template => #1.
- [x] Remove redundant configuration files => #3.
- [x] Put `App.tsx` in `src` directory => #4.
- [x] Upgrade Yarn to Berry => #5.
- [ ] Setup linting => redirected to #6.
- [ ] Setup Jest => redirected to #7.
- [ ] Setup CI => redirected to #8.

**Comment by noisypigeon** [comment]
I've completed the tasks crucial to getting started. #6, #7, and #8 will be completed later.
